2022-10-22 19:33:44 Error: [ParseError] syntax error, unexpected '}', expecting ';' (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:51)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(621): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Controller\ClientesController), 3, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(App\Controller\ClientesController), 4, 0)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(App\Controller\ClientesController), 4)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#32 {main}
Request URL: /clientes/add
Referer URL: http://localhost/Curso-PHP/clientes


2022-10-22 19:34:30 Error: [ParseError] syntax error, unexpected '}', expecting ';' (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:51)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:34:31 Error: [ParseError] syntax error, unexpected '}', expecting ';' (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:51)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:34:32 Error: [ParseError] syntax error, unexpected '}', expecting ';' (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:51)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:34:56 Error: [ParseError] syntax error, unexpected '}', expecting ';' (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:51)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:34:57 Error: [ParseError] syntax error, unexpected '}', expecting ';' (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:51)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:35:11 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:47)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:36:26 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:47)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:36:28 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:47)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:11 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:12 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:12 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:13 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:13 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:28 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:28 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:29 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


2022-10-22 19:38:29 Error: [ParseError] syntax error, unexpected 'protected' (T_PROTECTED), expecting end of file (C:\xampp\htdocs\Curso-PHP\src\Model\Entity\Cliente.php:48)
#0 C:\xampp\htdocs\Curso-PHP\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Model\\Entit...')
#2 [internal function]: spl_autoload_call('App\\Model\\Entit...')
#3 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(796): class_exists('App\\Model\\Entit...')
#4 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\ORM\Table.php(3119): Cake\ORM\Table->getEntityClass()
#5 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\ORM\Table->__debugInfo()
#6 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(App\Model\Table\ClientesTable), 1, 2)
#7 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(573): Cake\Error\Debugger::_export(Object(App\Model\Table\ClientesTable), 2, 1)
#8 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(608): Cake\Error\Debugger::_array(Array, 2, 1)
#9 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(532): Cake\Error\Debugger::_object(Object(Cake\ORM\Query), 3, 1)
#10 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Debugger.php(497): Cake\Error\Debugger::_export(Object(Cake\ORM\Query), 4, 0)
#11 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Element\exception_stack_trace.ctp(37): Cake\Error\Debugger::exportVar(Object(Cake\ORM\Query), 4)
#12 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#14 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1879): Cake\View\View->_render('C:\\xampp\\htdocs...', Array)
#15 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(783): Cake\View\View->_renderElement('C:\\xampp\\htdocs...', Array, Array)
#16 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Template\Layout\dev_error.ctp(220): Cake\View\View->element('exception_stack...')
#17 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1435): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(1393): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#19 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(939): Cake\View\View->_render('C:\\xampp\\htdocs...')
#20 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\View\View.php(897): Cake\View\View->renderLayout('', 'dev_error')
#21 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Controller\Controller.php(791): Cake\View\View->render('error500', NULL)
#22 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(369): Cake\Controller\Controller->render('error500')
#23 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(378): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#24 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(243): Cake\Error\ExceptionRenderer->_outputMessage('parseError')
#25 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(120): Cake\Error\ExceptionRenderer->render()
#26 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(102): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ParseError), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(53): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 C:\xampp\htdocs\Curso-PHP\vendor\cakephp\cakephp\src\Http\Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#32 C:\xampp\htdocs\Curso-PHP\webroot\index.php(40): Cake\Http\Server->run()
#33 {main}
Request URL: /clientes
Referer URL: http://localhost/Curso-PHP/clientes/view/1


